---
- block: # Check for telegraf.conf

  - name: Check if telegraf configuration file is exists
    stat:
      path: "{{ automated_docker_telegraf_host_config_file_path }}"
    register: automated_docker_telegraf_config_check


- block: # Copy all configuration files to telegraf container

  - name: Install python
    raw: python --version || (apk update && apk add python)
    delegate_to: "{{ automated_docker_run.name }}"
    when: automated_docker_telegraf_config_check.stat.exists

  - name: Copy telegraf configuration file
    copy:
      src: "{{ automated_docker_telegraf_host_config_file_path }}/"
      dest: "{{ automated_docker_telegraf_config_path }}/"
    delegate_to: "{{ automated_docker_run.name }}"
    when: automated_docker_telegraf_config_check.stat.exists
    notify: Restart container
